# Generated by Django 6.0.5 on 2026-05-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='Fresher', max_length=100),
        ),
    ]
